version: '3.4'

services:
  #Datas
  sqldata:
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y
    ports:
      - "6433:1433"
    volumes:
      - k2bm-sqldata:/var/opt/mssql

  #Event Bus
  k2bm-rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"
  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "6340:80"

  #Servers
  gps-listner:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=${K2BM_AZURE_SERVICE_BUS:-k2bm-rabbitmq}
      - EventBusUserName=${K2BM_SERVICE_BUS_USERNAME}
      - EventBusPassword=${K2BM_SERVICE_BUS_PASSWORD}
      - AzureServiceBusEnabled=False
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - Serilog__MinimumLevel__Override__K2BM.Microservices.BuildingBlocks.EventBusRabbitMQ=Verbose
      - Serilog__MinimumLevel__Override__gps-listner=Verbose
      - PORT=80
      - PATH_BASE=/gps-listner
    ports:
      - "6101:6101"


  #Services
  gps-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=${ESHOP_AZURE_CATALOG_DB:-Server=sqldata;Database=K2BM.Microservices.Services;User Id=sa;Password=Your_password123}
      - PicBaseUrl=${ESHOP_STORAGE_CATALOG_URL}

      - IdentityServerUrl=http://k2bm-identity-authserver
      - IdentityUrlExternal=http://${K2BM_EXTERNAL_DNS_NAME_OR_IP}:6108 #5103

      - EventBusConnection=${ESHOP_AZURE_SERVICE_BUS:-k2bm-rabbitmq}
      - EventBusUserName=${ESHOP_SERVICE_BUS_USERNAME}
      - EventBusPassword=${ESHOP_SERVICE_BUS_PASSWORD}

      - AzureStorageAccountName=${ESHOP_AZURE_STORAGE_CATALOG_NAME}
      - AzureStorageAccountKey=${ESHOP_AZURE_STORAGE_CATALOG_KEY}

      - UseCustomizationData=True
      - AzureServiceBusEnabled=False
      - AzureStorageEnabled=False

      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - Serilog__MinimumLevel__Override__K2BM.Microservices.BuildingBlocks.EventBusRabbitMQ=Verbose
      - Serilog__MinimumLevel__Override__gps-api=Verbose
      - GRPC_PORT=81
      - PORT=80
      - PATH_BASE=/gps-api
    ports:
      - "6102:80"
      - "8102:81"

  #k2bm-identity-api:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - ASPNETCORE_URLS=http://0.0.0.0:80
  #    - ConnectionString=${K2BM_AZURE_IDENTITY_DB:-Server=sqldata;Database=K2BM.Microservices.Services;User Id=sa;Password=Your_password123}
      
  #    - MvcClient=http://${K2BM_EXTERNAL_DNS_NAME_OR_IP}:5120
  #    - WebRentCarAggClient=http://${K2BM_EXTERNAL_DNS_NAME_OR_IP}:5130
  #    - GpsApiClient=http://${K2BM_EXTERNAL_DNS_NAME_OR_IP}:5102

  #    #- SpaClient=http://${K2BM_EXTERNAL_DNS_NAME_OR_IP}:5104
  #    #- XamarinCallback=http://${K2BM_PROD_EXTERNAL_DNS_NAME_OR_IP}:5105/xamarincallback
  #    #- BasketApiClient=http://${K2BM_EXTERNAL_DNS_NAME_OR_IP}:5103
  #    #- OrderingApiClient=http://${K2BM_EXTERNAL_DNS_NAME_OR_IP}:5102
  #    #- MobileShoppingAggClient=http://${K2BM_EXTERNAL_DNS_NAME_OR_IP}:5120
  #    #- WebhooksApiClient=http://${K2BM_EXTERNAL_DNS_NAME_OR_IP}:5113
  #    #- WebhooksWebClient=http://${K2BM_EXTERNAL_DNS_NAME_OR_IP}:5114
  #    - UseCustomizationData=True
  #    - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
  #    - OrchestratorType=${ORCHESTRATOR_TYPE}
  #  ports:
  #    - "6103:80"

  #k2bm-identity-authuser:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - ASPNETCORE_URLS=http://0.0.0.0:80
  #    - ConnectionString=${K2BM_AZURE_IDENTITY_DB:-Server=sqldata;Database=K2BM.Microservices.Services;User Id=sa;Password=Your_password123;MultipleActiveResultSets=true;}
  #    - IdentityServerUrl=http://k2bm-identity-authserver
  #    - UseCustomizationData=True
  #  ports:
  #    - "6109:80"

  k2bm-identity-authuser:
    environment:
        ASPNETCORE_ENVIRONMENT: "Development"
        ConnectionStrings__ClassifiedAds: ${K2BM_AZURE_IDENTITY_DB:-Server=sqldata;Database=K2BM.Microservices.Services;User Id=sa;Password=Your_password123;MultipleActiveResultSets=true;}
        IdentityServerAuthentication__Authority: http://${K2BM_EXTERNAL_DNS_NAME_OR_IP}:6110
        IdentityServerAuthentication__RequireHttpsMetadata: "false"
    ports:
      - "6109:80"

  k2bm-identity-authserver:
    environment:
        ASPNETCORE_ENVIRONMENT: "Development"
        ConnectionStrings__ClassifiedAds: ${K2BM_AZURE_IDENTITY_DB:-Server=sqldata;Database=K2BM.Microservices.Services;User Id=sa;Password=Your_password123;MultipleActiveResultSets=true;}
        CookiePolicyOptions__IsEnabled: "true"
        CookiePolicyOptions__MinimumSameSitePolicy: "Lax"
        CookiePolicyOptions__Secure: "None"
        MessageBroker__Provider: "RabbitMQ"
        MessageBroker__RabbitMQ__HostName: "rabbitmq"
        MvcClient: http://${K2BM_EXTERNAL_DNS_NAME_OR_IP}:6120
        WebRentCarAggClient: http://${K2BM_EXTERNAL_DNS_NAME_OR_IP}:6130
        GpsApiClient: http://${K2BM_EXTERNAL_DNS_NAME_OR_IP}:6102
        #Services__AuditLog__Grpc: ${Services__AuditLog__Grpc}
        #Services__Identity__Grpc: ${Services__Identity__Grpc}
        #Services__Notification__Grpc: ${Services__Notification__Grpc}

  #k2bm-identityServer-api:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - ASPNETCORE_URLS=http://0.0.0.0:80
  #    - ConnectionString=${K2BM_AZURE_IDENTITY_DB:-Server=sqldata;Database=K2BM.Microservices.Services;User Id=sa;Password=Your_password123;MultipleActiveResultSets=true;}

  #    - CookiePolicyOptions__IsEnabled:"true"
  #    - CookiePolicyOptions__MinimumSameSitePolicy:"Lax"
  #    - CookiePolicyOptions__Secure:"None"
      
  #    - MvcClient=http://${K2BM_EXTERNAL_DNS_NAME_OR_IP}:5120
  #    - WebRentCarAggClient=http://${K2BM_EXTERNAL_DNS_NAME_OR_IP}:5130
  #    - GpsApiClient=http://${K2BM_EXTERNAL_DNS_NAME_OR_IP}:5102

  #    - SpaClient=http://${K2BM_EXTERNAL_DNS_NAME_OR_IP}:5104
  #    - XamarinCallback=http://${K2BM_PROD_EXTERNAL_DNS_NAME_OR_IP}:5105/xamarincallback
  #    - BasketApiClient=http://${K2BM_EXTERNAL_DNS_NAME_OR_IP}:5108 #5103
  #    - OrderingApiClient=http://${K2BM_EXTERNAL_DNS_NAME_OR_IP}:5102
  #    - MobileShoppingAggClient=http://${K2BM_EXTERNAL_DNS_NAME_OR_IP}:5120
  #    - WebhooksApiClient=http://${K2BM_EXTERNAL_DNS_NAME_OR_IP}:5113
  #    - WebhooksWebClient=http://${K2BM_EXTERNAL_DNS_NAME_OR_IP}:5114
  #    - UseCustomizationData=True
  #    - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
  #    - OrchestratorType=${ORCHESTRATOR_TYPE}
  #  ports:
  #    - "6108:80"

  rentcar-catalog-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=${K2BM_AZURE_CATALOG_DB:-Server=sqldata;Database=K2BM.Microservices.Services;User Id=sa;Password=Your_password123}
      - PicBaseUrl=${K2BM_STORAGE_CATALOG_URL}

      - EventBusConnection=${K2BM_AZURE_SERVICE_BUS:-k2bm-rabbitmq}
      - EventBusUserName=${K2BM_SERVICE_BUS_USERNAME}
      - EventBusPassword=${K2BM_SERVICE_BUS_PASSWORD}

      - AzureStorageAccountName=${K2BM_AZURE_STORAGE_CATALOG_NAME}
      - AzureStorageAccountKey=${K2BM_AZURE_STORAGE_CATALOG_KEY}

      - UseCustomizationData=True
      - AzureServiceBusEnabled=False
      - AzureStorageEnabled=False

      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - GRPC_PORT=81
      - PORT=80
      - PATH_BASE=/rentcar-catalog-api
    ports:
      - "6105:80"
      - "8105:81"


  #Aggregators And Gateyway

  webrentcaragg:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

      - urls__rentCarCatalog=http://rentcar-catalog-api
      - urls__identityServerUrl=http://k2bm-identity-authserver
      - urls__gps=http://gps-api

      - urls__grpcRentCarCatalog=http://rentcar-catalog-api:81
      - urls__grpcGps=http://gps-api:81

      - RentCarCatalogUrlHC=http://rentcar-catalog-api/hc
      - IdentityServerUrlHC=http://k2bm-identity-authserver/hc
      - GpsUrlHC=http://gps-api/hc

      - IdentityUrlExternal=http://${K2BM_EXTERNAL_DNS_NAME_OR_IP}:6110 #5103
    ports:
      - "6130:80"

  webrentcarapigw:
    volumes:
      - ./ApiGateways/Envoy/config/webrentcar:/etc/envoy
    ports:
    - "6131:80"
    - "15131:8001"


  #Clients
  webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80

      - PurchaseUrl=http://webrentcarapigw
      - IdentityServerUrl=http://${K2BM_EXTERNAL_DNS_NAME_OR_IP}:6110 #5103

      - IdentityServerUrlHC=http://k2bm-identity-authserver/hc
      - RentCarCatalogUrlHC=http://rentcar-catalog-api/hc

      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
    ports:
      - "6120:80"

  webstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80

      - HealthChecksUI__HealthChecks__1__Name=Rent Car Catalog HTTP Check
      - HealthChecksUI__HealthChecks__1__Uri=http://rentcar-catalog-api/hc
      - HealthChecksUI__HealthChecks__2__Name=Identity server HTTP Check
      - HealthChecksUI__HealthChecks__2__Uri=http://k2bm-identity-authserver/hc
      - HealthChecksUI__HealthChecks__3__Name=Gps Api HTTP Check
      - HealthChecksUI__HealthChecks__3__Uri=http://gps-api/hc
      - HealthChecksUI__HealthChecks__4__Name=Gps Listner HTTP Check
      - HealthChecksUI__HealthChecks__4__Uri=http://gps-listner/hc

      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "6121:80"

  webspa:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80

      - IdentityUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:6110
      - PurchaseUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:6131

      - IdentityUrlHC=http://k2bm-identity-authserver/hc

      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      
    ports:
      - "6122:80"


#Volumes
volumes:
  k2bm-sqldata:
    external: false

