entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic
    watch: true

log:
  level: DEBUG
  filePath: "/var/log/traefik.log"
  format: json

accessLog:
  filePath: "/var/log/traefik-access.log"
  format: json

certificatesResolvers:
  default:
    acme:
      email: ton-email@exemple.com
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: http
