entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

log:
  level: DEBUG
  filePath: "/var/log/traefik.log"
  format: json

accessLog:
  filePath: "/var/log/traefik-access.log"
  format: json

certificatesResolvers:
  default:
    acme:
      email: m.bidouh@gmail.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: http


